# Generated by Django 3.2.7 on 2021-11-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='course/documents/%Y/%m/%d'),
        ),
    ]
