# Generated by Django 3.2.7 on 2021-11-12 22:17

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20211105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=course.models.upload_path),
        ),
    ]
